"""Add media fields to items

Revision ID: 41fceeeff981
Revises: 1a31ce608336
Create Date: 2024-12-19 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '41fceeeff981'
down_revision = '1a31ce608336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
    op.add_column('item', sa.Column('video_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
    op.add_column('item', sa.Column('media_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'media_type')
    op.drop_column('item', 'video_url')
    op.drop_column('item', 'image_url')
    # ### end Alembic commands ### 